services:
  - type: web
    name: noblehuman-web
    plan: starter
    runtime: node
    buildCommand: npm ci --include=dev && npx prisma migrate deploy && npx prisma db seed && npm run build && npm prune --production
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - fromGroup: noblehuman-env
      - key: DATABASE_URL
        fromDatabase:
          name: noblehuman-db
          property: connectionString

databases:
  - name: noblehuman-db
    plan: basic-256mb
    postgresMajorVersion: 17

envVarGroups:
  - name: noblehuman-env
    envVars:
      - key: OPENAI_API_KEY
        sync: false